package models

import (
	"time"

	"github.com/shopspring/decimal"
)

// Transaction represents a completed money transfer between two accounts.
// Once created, transactions are immutable and serve as an audit trail.
//
// Business rules:
//   - TransactionID is auto-generated by the database
//   - Amount must be positive (enforced at database level)
//   - Source and destination must be different accounts
//   - Both source and destination accounts must exist
//
// Uses db tags for go-kit/pgx reflection-based CRUD operations.
type Transaction struct {
	// TransactionID is the unique identifier, auto-generated by the database.
	TransactionID int64 `db:"transaction_id" id:"true" json:"transaction_id"`

	// SourceAccountID is the account from which funds are transferred.
	SourceAccountID int64 `db:"source_account_id" json:"source_account_id"`

	// DestinationAccountID is the account to which funds are transferred.
	DestinationAccountID int64 `db:"destination_account_id" json:"destination_account_id"`

	// Amount is the transfer amount. Uses decimal.Decimal for precision.
	Amount decimal.Decimal `db:"amount" json:"amount"`

	// CreatedAt is the timestamp when the transaction was created.
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

// TableName returns the database table name for Transaction.
// This can be used by go-kit/pgx for table resolution.
func (t Transaction) TableName() string {
	return "transactions"
}
